name: SonarQube Local Analysis

on:
  workflow_dispatch: # Manually trigger this workflow
  push:
    branches: [main, develop]

env:
  SONAR_HOST_URL: http://localhost:9000

jobs:
  sonarqube-local:
    runs-on: self-hosted # This requires a self-hosted runner on your machine

    steps:
      - name: Debug Environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "User: $(whoami)"
          echo "Node version: $(node --version 2>/dev/null || echo 'Node.js not found')"
          echo "NPM version: $(npm --version 2>/dev/null || echo 'NPM not found')"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify checkout
        run: |
          echo "Working directory after checkout: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Package.json exists: $(test -f package.json && echo 'YES' || echo 'NO')"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Wait for SonarQube to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:9000/api/system/status; do sleep 5; done'

      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v8
        with:
          version: 5.0.1.3006

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
            -Dproject.settings=sonar-project.local.properties \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
